<p><a href="<?php echo $this->url(
    array(
        'controller' => 'sentemails',
        'action'     => 'send'
  
    ),
    'default',
    true) ?>">Click here to send an email</a></p>

<table>
    <caption><b>Sent Emails</b></caption>
    <tr>
        <td><b>Email</b></td>
	    <td><b>Name</b></td>
        <td><b>Content of Email</b></td>
	    <td><b>Date and Time Sent</b></td>
	</tr>
    <?php foreach ($this->entries as $entry): ?>
	<tr>
    <td><?php echo $this->escape($entry->email) ?></td>
	<td><?php echo $this->escape($entry->name) ?></td>
    <td><?php echo $this->escape($entry->content) ?></td>
	<td><?php echo $this->escape($entry->datetime) ?></td>
	</tr>
    <?php endforeach ?>
</dl>
<br>
